### ISSUE TITLE
Unsuported distro (Linux Mint)

### ISSUE THREAD

**Issue by PastTenseOfDraw** [evert/communauto-car-notify#3]
Hello I'm trying to communauto- car-notify work but I don't the Linxu Mint is supported yet. I'm also new to Linux so it may also be user error.

**Comment by evert** [comment]
Hey! Happy to help you make this work and make the adaptations. But I'll need a hand to understand the issue(s). What happens when you run the script?

**Comment by PastTenseOfDraw** [comment]
"No such file or directory"

I was able to install both geoclue2-demos and nodejs.

I realized that I'm actually not sure of the steps to run the script.

**Comment by evert** [comment]
Normally, you would do a git clone, cd into the directory and then run `./run.mjs`

is that what you did? I would expect there to be more output. Perhaps you can share everything you got, or maybe a screenshot of your terminal?

**Comment by PastTenseOfDraw** [comment]
I didn't git clone, cd into the directory and then run `./run.mjs` before. Still very new to Linux. 

I think I have that part right now. 

```
drew@CurbCuts:~/Downloads$ cd communauto-car-notify-main
drew@CurbCuts:~/Downloads/communauto-car-notify-main$ pwd
/home/drew/Downloads/communauto-car-notify-main
drew@CurbCuts:~/Downloads/communauto-car-notify-main$ ls
image  README.md  run.mjs
drew@CurbCuts:~/Downloads/communauto-car-notify-main$ ./run.mjs
bash: ./run.mjs: Permission denied
drew@CurbCuts:~/Downloads/communauto-car-notify-main$ ./run.mjs
file:///home/drew/Downloads/communauto-car-notify-main/run.mjs:74
  const cars = await getCars(location);
               ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

**Comment by evert** [comment]
That's progress! Unfortunately the issue you have now is a Node version that's too old. I'm a little surprised because this was added years ago, so I would expect an up-to-date Mint to ship with a somewhat recent node version.

If you're willing to keep going, try to upgrade Node. If Mint does not offer an up-to-date version, tools like [nvm](https://github.com/nvm-sh/nvm) could potentially do this.

**Comment by PastTenseOfDraw** [comment]
I'm learning a lot, and you have been helpful, I'm going to keep at it.

It could not determine my current location, so tried installing geoclue-2-demo again, but the same error occurred.

```
drew@CurbCuts:~$ sudo apt-get install geoclue-2-demo
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
geoclue-2-demo is already the newest version (2.5.7-3ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
drew@CurbCuts:~$ cd Downloads
drew@CurbCuts:~/Downloads$ ls
c2R-A6j7                        org.kde.okular.flatpakref
communauto-car-notify-main      steam_latest.deb
communauto-car-notify-main.zip  syncthing-linux-amd64-v1.27.9
linux_treesheets_clang++.zip    syncthing-linux-amd64-v1.27.9.tar.gz
linux_treesheets_g++.zip        talon-linux.tar.xz
node-v20.16.0-linux-x64.tar.xz  TreeSheets-relocatable
drew@CurbCuts:~/Downloads$ cd communauto-car-notify-main
drew@CurbCuts:~/Downloads/communauto-car-notify-main$ ./run.mjs
Using City Branch: toronto. Branch ID: 3
Getting current location
file:///home/drew/Downloads/communauto-car-notify-main/run.mjs:169
    throw new Error('Could not determine current location');
          ^

Error: Could not determine current location
    at getLocation (file:///home/drew/Downloads/communauto-car-notify-main/run.mjs:169:11)
    at file:///home/drew/Downloads/communauto-car-notify-main/run.mjs:68:96
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:485:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:109:5)

Node.js v22.5.1
```

**Comment by NoahMLoomis** [comment]
Seems to be an issue with the geoclue package running on linux, was also unable to run `run.mjs`. I'd suggest having an option to enter the lat/long manually if the object returned from geoclue is `undefined`.

**Comment by evert** [comment]
I only run on Linux, I'm just on Fedora. This is probably an issue with the path to this binary being something different. Happy to merge any (tested) changes to this package but I don't have time to further investigate this.

**Comment by NoahMLoomis** [comment]
Seems that Mozilla locations services has been discontinued, https://unix.stackexchange.com/questions/778391/geoclue-failed-to-query-location-not-found

**Comment by evert** [comment]
My geoclue at least falls back on geoip and doesn't outright fail.

**Comment by NoahMLoomis** [comment]
Strange, I'll try to reproduce on federa

**Comment by evert** [comment]
I'm 90% sure the reason it fails for you because i hardcoded the path to geoclue to how it is on fedora, and it's somewhere else on your distro. 

Does `/usr/libexec/geoclue-2.0/demos/where-am-i` work?

**Comment by NoahMLoomis** [comment]
Sorry forgot to mention it, I checked and yes it's at the same location. Running `where-am-i` times out eventually and shows nothing

**Comment by evert** [comment]
@NoahMLoomis ah annoying. Then yeah for this utility to work for you, there's two possible paths:

* Figure out if you can get `where-am-i` to work for you
* Find another provider for this information

Also you _can_ provide a `--location` or `-l` argument. Just has to be a comma-separated lat/lng.

**Comment by NoahMLoomis** [comment]
ah nice didn't realize there was an `l` flat. That will work in the meantime while I figure out why `where-i-am` doesn't work. Thanks for the help!

**Comment by NoahMLoomis** [comment]
#5 Should fix this issue since the app would no longer rely on `geoclue-2`
